#!/bin/bash

mkdir -p urls

scrapy runspider spiders/investigation.py
scrapy runspider spiders/honor.py
scrapy runspider spiders/admiration.py
scrapy runspider spiders/experience.py

sort spiders/urls/song_urls.txt | uniq > spiders/urls/unique_song_urls.txt

scrapy runspider spiders/meditation.py 
