#!/bin/bash

# launch ubuntu instances TODO this could be general
gcloud compute instances create brahe

# need to wait for instances to start running
sleep 15

# get instance domains
INSTANCES=$(gcloud compute instances list | grep -v NAME | cut -d ' ' -f1)
for instance in $INSTANCES; do

	# install cassandra on each domain
	gcloud compute ssh $instance --command \
	'printf "\ndeb http://www.apache.org/dist/cassandra/debian 21x main\ndeb-src http://www.apache.org/dist/cassandra/debian 21x main" | \
	sudo tee -a /etc/apt/sources.list && gpg --keyserver pgp.mit.edu --recv-keys 749D6EEC0353B12C && gpg --export --armor 749D6EEC0353B12C | \
	sudo apt-key add - && sudo apt-get update && sudo apt-get -y install cassandra'

done

#echo
#echo "Cassandra installed, giving it a second before configuring"
#echo
#
#sleep 30
#
## shut cassandra down
#for domain in $DOMAINS; do
#
#	ssh -oStrictHostKeyChecking=no -i $AWS_INSTANCE_KEY ubuntu@$domain \
#	'sudo service cassandra stop && sudo rm -rf /var/lib/cassandra/data/system/*'
#
#done
#
## set cassandra config
#for domain in $DOMAINS; do
#
#	scp -i $AWS_INSTANCE_KEY $PWD/cassandra.yaml ubuntu@$domain:/etc/cassandra/cassandra.yaml
#
#done
#
## start cassandra up
#for domain in $DOMAINS; do
#
#	ssh -oStrictHostKeyChecking=no -i $AWS_INSTANCE_KEY ubuntu@$domain 'sudo service cassandra start'
#
#done
